import type { Contact } from "./types";

export const seedContacts: Contact[] = [
  {
    id: "seed-inner-1",
    name: "Jordan Hale",
    tier: 0,
    email: "jordan.hale@email.com",
    phone: "(312) 555-0142",
    company: "Self-employed",
    birthday: "March 12",
    notes: [
      {
        id: "seed-note-1",
        text: "Weekly coffee on Saturdays. Knows the whole family.",
        date: "1/15/2026",
      },
    ],
  },
  {
    id: "seed-inner-2",
    name: "Sam Rivera",
    tier: 0,
    email: "sam.rivera@email.com",
    phone: "(415) 555-0198",
    company: "",
    birthday: "July 4",
    notes: [
      {
        id: "seed-note-2",
        text: "Best friend since college. Always shows up.",
        date: "2/2/2026",
      },
    ],
  },
  {
    id: "seed-inner-3",
    name: "Alex Chen",
    tier: 0,
    email: "alex.chen@email.com",
    phone: "(206) 555-0177",
    company: "Northwind Labs",
    birthday: "November 21",
    notes: [],
  },
  {
    id: "seed-close-1",
    name: "Taylor Brooks",
    tier: 1,
    email: "taylor.brooks@email.com",
    phone: "(646) 555-0133",
    company: "Brightside Media",
    birthday: "April 9",
    notes: [
      {
        id: "seed-note-3",
        text: "Met through hiking group. Great travel buddy.",
        date: "3/10/2026",
      },
    ],
  },
  {
    id: "seed-close-2",
    name: "Morgan Lee",
    tier: 1,
    email: "morgan.lee@email.com",
    phone: "",
    company: "City Hospital",
    birthday: "August 30",
    notes: [],
  },
  {
    id: "seed-close-3",
    name: "Casey Quinn",
    tier: 1,
    email: "",
    phone: "(773) 555-0160",
    company: "",
    birthday: "January 18",
    notes: [],
  },
  {
    id: "seed-friend-1",
    name: "Riley Patel",
    tier: 2,
    email: "riley.patel@email.com",
    phone: "(512) 555-0111",
    company: "Oak Street Design",
    birthday: "",
    notes: [],
  },
  {
    id: "seed-friend-2",
    name: "Jamie Soto",
    tier: 2,
    email: "jamie.soto@email.com",
    phone: "(305) 555-0184",
    company: "Freelance photographer",
    birthday: "May 25",
    notes: [
      {
        id: "seed-note-4",
        text: "Invite to next game night.",
        date: "4/1/2026",
      },
    ],
  },
  {
    id: "seed-friend-3",
    name: "Drew Kim",
    tier: 2,
    email: "",
    phone: "(847) 555-0129",
    company: "Lincoln High PTA",
    birthday: "",
    notes: [],
  },
  {
    id: "seed-acq-1",
    name: "Cameron Walsh",
    tier: 3,
    email: "c.walsh@workmail.com",
    phone: "",
    company: "Harbor Consulting",
    birthday: "",
    notes: [],
  },
  {
    id: "seed-acq-2",
    name: "Avery Nguyen",
    tier: 3,
    email: "",
    phone: "(972) 555-0155",
    company: "Neighborhood block captain",
    birthday: "October 3",
    notes: [],
  },
  {
    id: "seed-acq-3",
    name: "Reese Donovan",
    tier: 3,
    email: "reese.d@email.com",
    phone: "(602) 555-0107",
    company: "Met at conference",
    birthday: "",
    notes: [],
  },
];
